export const heads = [
    'PID',
    "Name",
    'User',
    'State',
    '%RAM',
];

export const data = [
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
    {
        pid: 'PID',
        name: "Name",
        user: 'User',
        state: 'State',
        ram: '%RAM',
    },
];